---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa
spec:
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      containers:
      - name: freeipa
        image: registry.redhat.io/rhel7/ipa-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: freeipa
spec:
  selector:
    app: freeipa
  ports:
  - port: 389
    targetPort: 389
